# This file was generated by GoReleaser. DO NOT EDIT.
cask "ctxloom" do
  desc "Context Loom - Weave context for AI coding agents"
  homepage "https://github.com/ctxloom/ctxloom"
  version "0.6.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ctxloom"

  on_macos do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.2/ctxloom_0.6.2_darwin_amd64.tar.gz"
      sha256 "3133c265ae68d80bed1c49ff76beff6d35e1ea0d8d2a0ce0fc7850ec1389f052"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.2/ctxloom_0.6.2_darwin_arm64.tar.gz"
      sha256 "2529e560d8eba8409cb879f9f03987a0d02280b9e036a633a8cce385d509ef0a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.2/ctxloom_0.6.2_linux_amd64.tar.gz"
      sha256 "9f0b28530def63acc909bcce5cd4f44bc52bb10777a5b476c6d5e67daa5ed044"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.2/ctxloom_0.6.2_linux_arm64.tar.gz"
      sha256 "bbb053cc07fe38baea6bac7962088c4970f5f0aa890d47cbfe871dd76a2c1e57"
    end
  end

  conflicts_with cask: [
      "ctxloom-full",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ctxloom"]
    end
  end

  # No zap stanza required
end
