# This file was generated by GoReleaser. DO NOT EDIT.
cask "ctxloom-full" do
  desc "Context Loom (full build with tree-sitter AST code compression)"
  homepage "https://github.com/ctxloom/ctxloom"
  version "0.6.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ctxloom"

  on_macos do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.2/ctxloom_0.6.2_darwin_amd64_full.tar.gz"
      sha256 "580523f334b8ca0f268f7100277303bc9bda7db44ea7c64c91a6164aac8212ce"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.2/ctxloom_0.6.2_darwin_arm64_full.tar.gz"
      sha256 "35b702f2d2a32e1b16841f39d9f28c700f235c0e39e9cafe8328f5a448c4a939"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.2/ctxloom_0.6.2_linux_amd64_full.tar.gz"
      sha256 "737d27312b82b92f45bede3aa7fada3316e1a2aefb894e2c067e4fee87e0f160"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.2/ctxloom_0.6.2_linux_arm64_full.tar.gz"
      sha256 "d5e099066a9891206852ebfc0373aa0556a4d0fd66529309fd331816486dc6a9"
    end
  end

  conflicts_with cask: [
      "ctxloom",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ctxloom"]
    end
  end

  # No zap stanza required
end
