# This file was generated by GoReleaser. DO NOT EDIT.
cask "ctxloom" do
  desc "Context Loom - Weave context for AI coding agents"
  homepage "https://github.com/ctxloom/ctxloom"
  version "0.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ctxloom"

  on_macos do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.1/ctxloom_0.6.1_darwin_amd64.tar.gz"
      sha256 "23ccf6e7029397dd1099d497122d8138ada76f79af22e0c37dec857b0f28a95c"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.1/ctxloom_0.6.1_darwin_arm64.tar.gz"
      sha256 "afe9d998eba4a415652614b5030c38ada4ccc2fe0c3ca866ed9c520f8969e1e8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.1/ctxloom_0.6.1_linux_amd64.tar.gz"
      sha256 "e26f8c1e0f600bb6f257717bd69e8c778716e2f41af5c08fb832359734561167"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.1/ctxloom_0.6.1_linux_arm64.tar.gz"
      sha256 "c35d59421d35bd40c700b407ed473284352c71d4bb2619b873508c17f54d3ed3"
    end
  end

  conflicts_with cask: [
      "ctxloom-full",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ctxloom"]
    end
  end

  # No zap stanza required
end
