# This file was generated by GoReleaser. DO NOT EDIT.
cask "ctxloom-full" do
  desc "Context Loom (full build with tree-sitter AST code compression)"
  homepage "https://github.com/ctxloom/ctxloom"
  version "0.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ctxloom"

  on_macos do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.1/ctxloom_0.6.1_darwin_amd64_full.tar.gz"
      sha256 "12525ca5ad16b41026d19980d694dfe922f12ec0cc9a495c3f7c9bfb9b7aa2b5"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.1/ctxloom_0.6.1_darwin_arm64_full.tar.gz"
      sha256 "996468fb708a5b6534ef638c2343ab1c9741fd85136016bf73e05540e3e567bd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.1/ctxloom_0.6.1_linux_amd64_full.tar.gz"
      sha256 "20ecd46e748056f5d2c129b0f67758f7e81bd27f3df5e655d9d6087d1985c3da"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.1/ctxloom_0.6.1_linux_arm64_full.tar.gz"
      sha256 "2957ac0808dcb42ada0d6268b26856a4ea1219a55f15dc34f4d4ec69f0c441c6"
    end
  end

  conflicts_with cask: [
      "ctxloom",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ctxloom"]
    end
  end

  # No zap stanza required
end
