# This file was generated by GoReleaser. DO NOT EDIT.
cask "ctxloom" do
  desc "Context Loom - Weave context for AI coding agents"
  homepage "https://github.com/ctxloom/ctxloom"
  version "0.6.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ctxloom"

  on_macos do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.4/ctxloom_0.6.4_darwin_amd64.tar.gz"
      sha256 "4a3c22b33bb682bea8287073b6bd7103ad726df4ba4dfe21fe0e988fb4728741"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.4/ctxloom_0.6.4_darwin_arm64.tar.gz"
      sha256 "b421b9aa87b94ad84389c6c42425f49ccb9e84e1491c6208198ce5d051f451a8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.4/ctxloom_0.6.4_linux_amd64.tar.gz"
      sha256 "89a356c697c9458929ecf851bc85da3a9548d19aa978837b54c0b0b27100810f"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.4/ctxloom_0.6.4_linux_arm64.tar.gz"
      sha256 "55540e5698ecd7a9f6029e375902edc4510cfb2e5952fbe5dc8f34ef904fc504"
    end
  end

  conflicts_with cask: [
      "ctxloom-full",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ctxloom"]
    end
  end

  # No zap stanza required
end
