# This file was generated by GoReleaser. DO NOT EDIT.
cask "ctxloom-full" do
  desc "Context Loom (full build with tree-sitter AST code compression)"
  homepage "https://github.com/ctxloom/ctxloom"
  version "0.6.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ctxloom"

  on_macos do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.4/ctxloom_0.6.4_darwin_amd64_full.tar.gz"
      sha256 "337a199b98fea693b27398d04dfed36188d66ae6bf40aa2b5cadb9100fb8eda3"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.4/ctxloom_0.6.4_darwin_arm64_full.tar.gz"
      sha256 "20f6ddb0cc606147e0fc19e12f49398aa090f4d1bdc44799bd1f3f378752e914"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.4/ctxloom_0.6.4_linux_amd64_full.tar.gz"
      sha256 "1f3b7e601d7fc368c290d080cd382e72b589d602d15e76cac50bb7799281ba3c"
    end
    on_arm do
      url "https://github.com/ctxloom/ctxloom/releases/download/v0.6.4/ctxloom_0.6.4_linux_arm64_full.tar.gz"
      sha256 "dbe4f5676e322f9cbe64c05fd1185df9e0d67da87dbef292e19ba4ed43aae154"
    end
  end

  conflicts_with cask: [
      "ctxloom",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ctxloom"]
    end
  end

  # No zap stanza required
end
