# This file was generated by GoReleaser. DO NOT EDIT.
cask "ltk" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "a633ac9cdc7a03ac03cd04b46b67c18a838b1d36b46ff5286eedfbf5362f0b76"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0e35200c8eadf2de11ee9a2b9ef8da644f8159cc2fc687bbfe2906bfd0cc225"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1151f4c1d4075c617e2de729a56301294bcd8ccf60a57f3075be5f71ba1d9493"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7f9f110dc809ade4e67e8c5b2d976857498d0e4364be1ba5b0765b2d40e3de59"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ltk"
  desc "Pre-tool hook that redirects an LLM agent's shell commands to the project's preferred command"
  homepage "https://github.com/ctxloom/llm-tool-killer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ltk"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ltk"]
    end
  end

  # No zap stanza required

end
