# This file was generated by GoReleaser. DO NOT EDIT.
cask "ltk" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "9ba46a27f0db7014ce5355d492720ee2f98b8cda66c08a172dc593e5bf9e908c"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec5bf16774ee4cd5da9c30ed71d06354c81804a31e172a9e7e5c6c340eedf9c6"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bc1569724c005af24b53b54aade1424b63539bfe91272b62cd6c0fb805137c63"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "88a65ab1bd81af345e2380ee6de2986e4e9fda95f758ea7ec9b9f4735ba64da1"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ltk"
  desc "Pre-tool hook that redirects an LLM agent's shell commands to the project's preferred command"
  homepage "https://github.com/ctxloom/llm-tool-killer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ltk"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ltk"]
    end
  end

  # No zap stanza required

end
