# This file was generated by GoReleaser. DO NOT EDIT.
cask "ltk" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "357ed012ec6bb1c973413ccfdd4ace186cfa44e55e08e3f6c66864d4fccb78cf"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "070894d3c7e2ee753d704ff36aa484b530d7ee4c932a481a468d8bde8da0e38e"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9457849efbec32136d07af2114cbb010a59fbf34b6818dddbc9880537cceafba"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f7a014ef414e6aa9a6d06609b7db5c1155709abc67ea3c79c3d60ac11ea5fda"
      url "https://github.com/ctxloom/llm-tool-killer/releases/download/v#{version}/ltk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ltk"
  desc "Pre-tool hook that redirects an LLM agent's shell commands to the project's preferred command"
  homepage "https://github.com/ctxloom/llm-tool-killer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ltk"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ltk"]
    end
  end

  # No zap stanza required

end
